---
version: '3'

services:
  db:
    image: postgres:10.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: myfinances
      POSTGRES_PASSWORD: myfinances
  web:
    image: gradle:5.4-jdk8-alpine
    command: ./gradlew bootRun
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
