---

spring:
  jpa:
    hibernate:
      ddl-auto: none # we use flyway
  datasource:
    platform: postgresql
    url: jdbc:postgresql://db:5432/myfinances
    database: mygfinances
    username: postgres
    password: myfinances
