CREATE TABLE accounts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  balance DECIMAL(18, 6) NOT NULL DEFAULT 0.0,
  color VARCHAR(16) NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NULL DEFAULT NULL
);
